repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-symlinks
      - id: check-xml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: name-tests-test
      - id: no-commit-to-branch
        args: ['--branch', 'main']
      - id: pretty-format-json
        args: ['--autofix']

  # Minimal formatting hooks
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: [--line-length=88]
        additional_dependencies: [click>=8.0.0]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
